export const ImagesLeft = [
	{ alt: 'TypeScript', index: 0, src: 'assets/ts.webp' },
	{ alt: 'JavaScript', index: 1, src: 'assets/js.webp' },
	{ alt: 'React', index: 2, src: 'assets/react.webp' },
	{ alt: 'Material UI', index: 3, src: 'assets/mui.webp' },
	{ alt: 'React Admin', index: 4, src: 'assets/react-admin.webp' },
	{ alt: 'React Hook Form', index: 5, src: 'assets/react-hook-form.webp' },
	{ alt: 'CASL', index: 6, src: 'assets/casl.webp' },
	{ alt: 'React Query', index: 7, src: 'assets/react-query.webp' },
	{ alt: 'Zod', index: 8, src: 'assets/zod.webp' },
	{ alt: 'Zustand', index: 9, src: 'assets/zustand.webp' },
	{ alt: 'Bootstrap', index: 10, src: 'assets/Bootstrap.webp' },
	{ alt: 'Framer', index: 11, src: 'assets/framer.webp' },
	{ alt: 'Framer Motion', index: 12, src: 'assets/framer-motion.webp' },
];

export const ImagesRight = [
	{ alt: 'React Native', index: 0, src: 'assets/react-native.webp' },
	{ alt: 'i18n', index: 1, src: 'assets/i18.webp' },
	{ alt: 'Axios', index: 2, src: 'assets/axios.webp' },
	{ alt: 'HTML', index: 3, src: 'assets/html.webp' },
	{ alt: 'CSS', index: 4, src: 'assets/css.webp' },
	{ alt: 'Git', index: 5, src: 'assets/git.webp' },
	{ alt: 'GitHub', index: 6, src: 'assets/github.webp' },
	{ alt: 'jQuery', index: 7, src: 'assets/jquery.webp' },
	{ alt: 'Photoshop', index: 8, src: 'assets/photoshop.webp' },
	{ alt: 'Illustrator', index: 9, src: 'assets/illustrator.webp' },
	{ alt: 'Paper', index: 10, src: 'assets/paper.webp' },
	{ alt: 'Figma', index: 11, src: 'assets/figma-logo.webp' },
];
